version: '2.3'

services:
  mela-nn:
    build:
      context: .
      dockerfile: ./build/mela-nn.Dockerfile
    runtime: nvidia
    dns:
      - 208.67.222.222
    volumes:
      - ./:/opt/out
  build-mela-nn:
    build:
      context: .
      dockerfile: ./build/build-mela-nn.Dockerfile
    runtime: nvidia
    dns:
      - 208.67.222.222
    volumes:
      - ./:/opt/out